### ISSUE TITLE
Add JsonConverterFactory

### ISSUE THREAD

**Issue by lazy-pr0grammer** [Jumman04/DataManager#4]
Currently it supports gson by default but I want to use `kotlinx.serialization` and it would be better if you add support for other json libraries too like moshi, jackson etc. 
You can create a ConverterFactory than extend it to create multiple converter factories. It will also let others to create their own converters.

**Comment by Jumman04** [comment]
Hi @lazy-pr0grammer ,

Thank you for your valuable suggestion! We’re excited to share that we’ve added support for multiple converters in the latest update. You can now choose from several built-in converters, including:

- FastJson  
- Gson  
- Jackson  
- JsonIter  
- LoganSquare  
- Moshi  

Moreover, you can create your own custom converter by implementing the `DataManager.Converter` interface. This enhancement provides flexibility and empowers developers to use the serialization library that best suits their needs.

Regarding your request for kotlinx.serialization, we looked into it, but unfortunately, it is not compatible with Java projects, which this library aims to support. However, we’re committed to ensuring extensibility, so feel free to implement your own converter if you’re using Kotlin in a hybrid setup!

Thank you again for your feedback—it truly helps us improve and adapt to developers' needs! Let us know if there’s anything else we can assist with.

Best regards,  
@Jumman04

**Comment by Jumman04** [comment]
Hi there,

I'm pleased to inform you that we've addressed your request by adding the `KotlinxSerializationConverter` class for enhanced serialization support! This allows for more flexible data handling alongside the existing options.

You can also create your own custom converters by implementing the `DataManager.Converter` interface, enabling a wider variety of JSON libraries to be integrated into your projects.

For more details, check out the commit [here](https://github.com/Jumman04/DataManager/commit/6049507f912e785f57dcd8d7c9a7f89f78b5de3f).

Thank you for your feedback!

Best regards,  
Jumman
